
if($<BUILD_ENV:firmware_test>)
	set(DEVICE_ARCH "x86")
	set(DEVICE_ARCH_FLAGS "-m32 ")
else()
	set(DEVICE_ARCH "x86_64")
	set(DEVICE_ARCH_FLAGS "-m64 ")
endif()

string(APPEND CMAKE_C_FLAGS ${DEVICE_ARCH_FLAGS})
string(APPEND CMAKE_CXX_FLAGS ${DEVICE_ARCH_FLAGS})
string(APPEND CMAKE_ASM_FLAGS ${DEVICE_ARCH_FLAGS})
string(APPEND CMAKE_EXE_LINKER_FLAGS ${DEVICE_ARCH_FLAGS})
add_definitions("-DDEVICE_ARCH=${DEVICE_ARCH} ")
